sudo: false
dist: trusty
language: python
python:
  - "2.7.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install flake8
  - travis_retry pip install -r requirements-dev.txt
script:
  - flake8 slackeventsapi
  - py.test --cov-report= --cov=slackeventsapi tests
after_success:
  - codecov -e $TRAVIS_PYTHON_VERSION